# Generated by Django 5.2.4 on 2025-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='voter_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
