# Generated by Django 5.2.4 on 2025-07-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_candidate_alter_userregister_voter_id_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedVoterID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
